### ISSUE TITLE
Invalid date in maintenance sensors

### ISSUE THREAD

**Issue by rpitera** [jeremywillans/ha-rest980-roomba#11]
Not sure if this is a bug or not, but I got no response in the forum thread so I'm asking here.

I struggled with getting this all to work, on one hand because I can't use packages due to the way I split my configs so I had to do everything manually and on the other hand, because I was doing this with the brand new i3 and at the time was under an NDA so I couldn't publicly ask for help.  Nonetheless I managed to get everything sorted for the most part and even have the map image working, though I still have a ways to go in getting it positioned properly.  

Thank you!  Your work is amazing and I love the information presented!

Now that the NDA has expired, I can finally ask for help with the one thing I can't seem to resolve - the maintenance sensors.   I have a working MQTT setup and discovery is working with the discovery_prefix option to the point where I was able to get to the step where you click on the check button card to create the sensors.

But mine show "Invalid Date" for all the maintenance sensor timestamp_friendly attributes and no data for the timestamp_timeout attribute in all but one sensor.  

As an example, here is the attributes for the sensor.vacuum_maint_clean_filter:

```
timestamp_friendly: Invalid Date
timeout: 10 days
timeout_timestamp: null
timeout_seconds: 864000
severity:
  - color: '#bf4060'
    value: '-10 days'
    seconds: -864000
  - color: '#bfb540'
    value: 0 days
    seconds: 0
friendly_name: vacuum_maint_clean_filter
icon: 'mdi:checkbox-marked'
device_class: timestamp
```

For the vacuum_maint_clean_wheel sensor however, I've got the following info:
```
timestamp: ''
timestamp_friendly: '12/31/1969, 7:00:00 PM'
timeout: 18 days
timeout_timestamp: 1555200
timeout_seconds: 1555200
severity:
  - color: '#bf4060'
    value: '-3 days'
    seconds: -259200
  - color: '#bfb540'
    value: 0 days
    seconds: 0
friendly_name: vacuum_maint_clean_wheel
icon: 'mdi:checkbox-marked'
device_class: timestamp
```
I'm not sure if this is because the i3 is new and needs a different approach or if the i3 simply doesn't keep track of maintenance or I have set something up incorrectly.   I've tried troubleshooting this myself looking at the output from http://my_ha_instance:3000/api/local/info/state with PostMan, looking at the traffic with MQTT explorer, etc. but I'm in over my head.

Can you suggest a troubleshooting approach or confirm that this won't work with the i3?  I got the impression that the maintenance sensor should work but wasn't sure if I set something up wrong or it just isn't supported.  For example, I know that (at the moment) room/region level cleaning isn't.

Thanks!
